name = "codecrafters_interpreter"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "0.62.1"
gleam_erlang = "1.3.0"
simplifile = "2.3.0"
argv = "1.0.2"

[dev-dependencies]
gleeunit = "1.6.1"
